# Generated by Django 4.0.6 on 2022-10-16 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['orgname'],
            },
        ),
        migrations.CreateModel(
            name='WhsePartTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldWICSID', models.IntegerField(null=True)),
                ('WhsePartType', models.CharField(max_length=50)),
                ('PartTypePriority', models.SmallIntegerField()),
                ('InactivePartType', models.BooleanField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WICS.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='org_SAPPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAPPlant', models.CharField(max_length=50)),
                ('SAPStorLoc', models.CharField(max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WICS.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldWICSID', models.IntegerField(null=True)),
                ('Material', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('oldWICSPartType', models.IntegerField(null=True)),
                ('SAPMaterialType', models.CharField(blank=True, max_length=100)),
                ('SAPMaterialGroup', models.CharField(blank=True, max_length=100)),
                ('Price', models.FloatField(null=True)),
                ('PriceUnit', models.PositiveIntegerField(null=True)),
                ('Notes', models.CharField(blank=True, max_length=250)),
                ('PartType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='WICS.whseparttypes')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations')),
            ],
            options={
                'ordering': ['org', 'Material'],
            },
        ),
        migrations.CreateModel(
            name='Count_Schedule_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldWICSID', models.IntegerField(null=True)),
                ('CountDate', models.DateField()),
                ('oldWICSMaterial', models.IntegerField(null=True)),
                ('Counter', models.CharField(blank=True, max_length=250)),
                ('Priority', models.CharField(blank=True, max_length=50)),
                ('ReasonScheduled', models.CharField(blank=True, max_length=250)),
                ('CMPrintFlag', models.BooleanField()),
                ('Notes', models.CharField(blank=True, max_length=250)),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WICS.materiallist')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations')),
            ],
            options={
                'ordering': ['org', 'CountDate', 'Material'],
            },
        ),
        migrations.CreateModel(
            name='ActualCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldWICSID', models.IntegerField()),
                ('CountDate', models.DateField()),
                ('CycCtID', models.CharField(blank=True, max_length=100)),
                ('oldWICSMaterial', models.IntegerField(null=True)),
                ('Counter', models.CharField(max_length=250)),
                ('CTD_QTY_Expr', models.CharField(max_length=500)),
                ('BLDG', models.CharField(blank=True, max_length=100)),
                ('LOCATION', models.CharField(blank=True, max_length=250)),
                ('PKGID_Desc', models.CharField(blank=True, max_length=250)),
                ('TAGQTY', models.CharField(blank=True, max_length=250)),
                ('FLAG_PossiblyNotRecieved', models.BooleanField()),
                ('FLAG_MovementDuringCount', models.BooleanField()),
                ('Notes', models.CharField(blank=True, max_length=250)),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WICS.materiallist')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations')),
            ],
            options={
                'ordering': ['org', 'CountDate', 'Material'],
            },
        ),
    ]
