# Generated by Django 4.1.1 on 2022-10-08 03:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("orgname", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="WhsePartTypes",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("oldID", models.IntegerField()),
                ("WhsePartType", models.CharField(max_length=50)),
                ("PartTypePriority", models.SmallIntegerField()),
                ("InactivePartType", models.BooleanField()),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WICS.organizations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="org_SAPPlant",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("SAPPlant", models.CharField(max_length=50)),
                ("SAPStorLoc", models.CharField(max_length=50)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WICS.organizations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialList",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("oldID", models.IntegerField()),
                ("Material", models.CharField(max_length=100)),
                ("Description", models.CharField(blank=True, max_length=250)),
                ("SAPMaterialType", models.CharField(blank=True, max_length=100)),
                ("SAPMaterialGroup", models.CharField(blank=True, max_length=100)),
                ("PossibleLocations", models.CharField(blank=True, max_length=250)),
                ("Notes", models.CharField(blank=True, max_length=250)),
                (
                    "PartType",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="WICS.whseparttypes",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="WICS.organizations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Count_Schedule_History",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("oldID", models.IntegerField()),
                ("CountDate", models.DateField()),
                ("Counter", models.CharField(max_length=250)),
                ("Priority", models.CharField(max_length=50)),
                ("ReasonScheduled", models.CharField(max_length=250)),
                ("CMPrintFlag", models.BooleanField()),
                ("Notes", models.CharField(max_length=250)),
                (
                    "Material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="WICS.materiallist",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="WICS.organizations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActualCounts",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("oldID", models.IntegerField()),
                ("CountDate", models.DateField()),
                ("CycCtID", models.CharField(max_length=100)),
                ("Counter", models.CharField(max_length=250)),
                ("CTD_QTY_Expr", models.CharField(max_length=500)),
                ("BLDG", models.CharField(blank=True, max_length=100)),
                ("LOCATION", models.CharField(blank=True, max_length=250)),
                ("PKGID_Desc", models.CharField(blank=True, max_length=250)),
                ("TAGQTY", models.CharField(blank=True, max_length=250)),
                ("FLAG_PossiblyNotRecieved", models.BooleanField()),
                ("FLAG_MovementDuringCount", models.BooleanField()),
                ("Notes", models.CharField(blank=True, max_length=250)),
                (
                    "Material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="WICS.materiallist",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="WICS.organizations",
                    ),
                ),
            ],
        ),
    ]
