# Generated by Django 4.0.6 on 2022-10-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Count_Schedule_History',
            new_name='CountSchedule',
        ),
    ]
