# Generated by Django 4.1.1 on 2022-10-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tempimport_MaterialList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Material", models.CharField(max_length=100)),
                ("Plant", models.CharField(max_length=50)),
                ("dummy_ValuationType", models.CharField(max_length=250)),
                ("Description", models.CharField(blank=True, max_length=250)),
                ("dummy_LastChange", models.DateField()),
                ("SAPMaterialType", models.CharField(blank=True, max_length=100)),
                ("SAPMaterialGroup", models.CharField(blank=True, max_length=100)),
                ("dummy_BaseUnit", models.CharField(max_length=250)),
                ("dummy_PurchasingGroup", models.CharField(max_length=250)),
                ("dummy_ABCIndicator", models.CharField(max_length=250)),
                ("dummy_MRPType", models.CharField(max_length=250)),
                ("dummy_ValuationClass", models.CharField(max_length=250)),
                ("dummy_Pricecontrol", models.CharField(max_length=250)),
                ("dummy_Price", models.CharField(max_length=250)),
                ("dummy_Currency", models.CharField(max_length=250)),
                ("dummy_Priceunit", models.CharField(max_length=250)),
                ("dummy_Createdby", models.CharField(max_length=250)),
            ],
        ),
    ]
