# Generated by Django 4.1.1 on 2022-10-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0002_tempimport_materiallist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tempimport_MaterialList",
        ),
    ]
