# Generated by Django 4.0.6 on 2022-10-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0002_counters_rename_count_schedule_history_countschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualcounts',
            name='FLAG_MovementDuringCount',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='actualcounts',
            name='FLAG_PossiblyNotRecieved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='actualcounts',
            name='oldWICSID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='countschedule',
            name='CMPrintFlag',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='whseparttypes',
            name='InactivePartType',
            field=models.BooleanField(null=True),
        ),
    ]
