# Generated by Django 4.0.6 on 2022-11-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0003_alter_actualcounts_flag_movementduringcount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counters',
        ),
        migrations.AddField(
            model_name='materiallist',
            name='TypicalContainerQty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='materiallist',
            name='TypicalPalletQty',
            field=models.IntegerField(null=True),
        ),
    ]
