# Generated by Django 4.1.1 on 2022-10-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0003_delete_tempimport_materiallist"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiallist",
            name="Price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="materiallist",
            name="PriceUnit",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
