# Generated by Django 4.0.6 on 2022-11-27 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0004_delete_counters_materiallist_typicalcontainerqty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualcounts',
            name='oldWICSID',
        ),
        migrations.RemoveField(
            model_name='actualcounts',
            name='oldWICSMaterial',
        ),
        migrations.RemoveField(
            model_name='countschedule',
            name='oldWICSID',
        ),
        migrations.RemoveField(
            model_name='countschedule',
            name='oldWICSMaterial',
        ),
        migrations.RemoveField(
            model_name='materiallist',
            name='oldWICSID',
        ),
        migrations.RemoveField(
            model_name='materiallist',
            name='oldWICSPartType',
        ),
        migrations.RemoveField(
            model_name='whseparttypes',
            name='oldWICSID',
        ),
        migrations.AlterField(
            model_name='actualcounts',
            name='org',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations'),
        ),
        migrations.AlterField(
            model_name='countschedule',
            name='org',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='TypicalContainerQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='TypicalPalletQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='org',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations'),
        ),
        migrations.AlterField(
            model_name='whseparttypes',
            name='InactivePartType',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whseparttypes',
            name='org',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='WICS.organizations'),
        ),
        migrations.CreateModel(
            name='SAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UpdateDate', models.DateField()),
                ('Material', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('Plant', models.CharField(blank=True, max_length=50)),
                ('SAPMaterialType', models.CharField(blank=True, max_length=100)),
                ('StorageLocation', models.CharField(blank=True, max_length=50)),
                ('BaseUnitofMeasure', models.CharField(blank=True, max_length=50)),
                ('Unrestricted', models.FloatField(blank=True, null=True)),
                ('Currency', models.CharField(blank=True, max_length=50)),
                ('ValueUnrestricted', models.FloatField(blank=True, null=True)),
                ('SpecialStock', models.CharField(blank=True, max_length=50)),
                ('Batch', models.CharField(blank=True, max_length=50)),
                ('org', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations')),
            ],
            options={
                'ordering': ['org', 'UpdateDate', 'Material'],
            },
        ),
        migrations.CreateModel(
            name='ActualLocationTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountDate', models.DateField()),
                ('Counter', models.CharField(max_length=250)),
                ('BLDG', models.CharField(blank=True, max_length=100)),
                ('LOCATION', models.CharField(blank=True, max_length=250)),
                ('PKGID_Desc', models.CharField(blank=True, max_length=250)),
                ('TAGQTY', models.CharField(blank=True, max_length=250)),
                ('Notes', models.CharField(blank=True, max_length=250)),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WICS.materiallist')),
                ('org', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations')),
            ],
            options={
                'ordering': ['org', 'CountDate', 'Material'],
            },
        ),
    ]
