# Generated by Django 4.0.6 on 2022-11-28 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0005_remove_actualcounts_oldwicsid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('SAPFile', models.FileField(upload_to='SAP/')),
                ('Notes', models.CharField(blank=True, max_length=255)),
                ('org', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='WICS.organizations')),
            ],
        ),
    ]
