# Generated by Django 4.0.6 on 2022-11-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0006_sapfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualcounts',
            name='LocationOnly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actualcounts',
            name='FLAG_MovementDuringCount',
            field=models.BooleanField(blank=-1, null=True),
        ),
        migrations.AlterField(
            model_name='actualcounts',
            name='FLAG_PossiblyNotRecieved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ActualLocationTracks',
        ),
    ]
