# Generated by Django 4.0.6 on 2022-12-04 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0007_actualcounts_locationonly_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sapfiles',
            options={'get_latest_by': 'uploaded_at'},
        ),
        migrations.AlterField(
            model_name='actualcounts',
            name='FLAG_MovementDuringCount',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sapfiles',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
