# Generated by Django 4.0.6 on 2022-12-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0008_alter_sapfiles_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sap',
            name='org',
        ),
        migrations.AlterField(
            model_name='countschedule',
            name='CMPrintFlag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='org_SAPPlant',
        ),
        migrations.DeleteModel(
            name='SAP',
        ),
    ]
