# Generated by Django 4.1.1 on 2022-12-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0009_remove_sap_org_alter_countschedule_cmprintflag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualcounts",
            name="FLAG_MovementDuringCount",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="actualcounts",
            name="FLAG_PossiblyNotRecieved",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="actualcounts",
            name="LocationOnly",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="countschedule",
            name="CMPrintFlag",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="whseparttypes",
            name="InactivePartType",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
