# Generated by Django 4.1.1 on 2022-12-23 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0010_alter_actualcounts_flag_movementduringcount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualcounts",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="WICS.organizations"
            ),
        ),
        migrations.AlterField(
            model_name="materiallist",
            name="PriceUnit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
