# Generated by Django 4.1.1 on 2023-01-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0011_alter_actualcounts_org_alter_materiallist_priceunit"),
    ]

    operations = [
        migrations.CreateModel(
            name="tmpMaterialListUpdate",
            fields=[
                (
                    "Material",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("Description", models.CharField(blank=True, max_length=250)),
                ("SAPMaterialType", models.CharField(blank=True, max_length=100)),
                ("SAPMaterialGroup", models.CharField(blank=True, max_length=100)),
                ("Price", models.FloatField(blank=True, null=True)),
                ("PriceUnit", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="sapfiles",
            name="SAPFile",
            field=models.FileField(upload_to="SAP\\"),
        ),
    ]
