# Generated by Django 4.1.1 on 2023-01-07 03:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0012_tmpmateriallistupdate_alter_sapfiles_sapfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAP_SOHRecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("Material", models.CharField(max_length=100)),
                ("Description", models.CharField(blank=True, max_length=250)),
                ("Plant", models.CharField(blank=True, max_length=20)),
                ("MaterialType", models.CharField(blank=True, max_length=50)),
                ("StorageLocation", models.CharField(blank=True, max_length=20)),
                ("BaseUnitofMeasure", models.CharField(blank=True, max_length=20)),
                ("Amount", models.FloatField(blank=True)),
                ("Currency", models.CharField(blank=True, max_length=20)),
                ("ValueUnrestricted", models.FloatField(blank=True)),
                ("SpecialStock", models.CharField(blank=True, max_length=20)),
                ("Batch", models.CharField(blank=True, max_length=20)),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="WICS.organizations",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at", "org", "Material"],
                "get_latest_by": "uploaded_at",
            },
        ),
    ]
