# Generated by Django 4.1.1 on 2023-01-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0013_sap_sohrecs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SAPFiles",
        ),
    ]
