# Generated by Django 4.1.1 on 2023-01-17 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0014_delete_sapfiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorksheetZones",
            fields=[
                ("zone", models.IntegerField(primary_key=True, serialize=False)),
                ("zoneName", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="actualcounts",
            name="CTD_QTY_Expr",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="Location_WorksheetZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=10)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="WICS.worksheetzones",
                    ),
                ),
            ],
        ),
    ]
