# Generated by Django 4.1.1 on 2023-02-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0015_worksheetzones_alter_actualcounts_ctd_qty_expr_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whseparttypes",
            options={"ordering": ["org", "WhsePartType"]},
        ),
        migrations.AlterField(
            model_name="location_worksheetzone",
            name="location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="whseparttypes",
            name="org",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="WICS.organizations",
            ),
        ),
    ]
