# Generated by Django 4.1.2 on 2023-03-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0017_alter_actualcounts_countdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WICSPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('Material_onlyview', 'For restricting Material Form to view only'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
