# Generated by Django 4.1.1 on 2023-03-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WICS", "0018_wicspermissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wicspermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("Material_onlyview", "For restricting Material Form to view only")
                ],
            },
        ),
    ]
