# Generated by Django 4.1.1 on 2023-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WICS", "0021_view_actualcounts_view_countschedule_view_foundat_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="countschedule",
            name="CSchdUNQ_org_CDate_Material",
        ),
        migrations.RemoveConstraint(
            model_name="materiallist",
            name="MatlListUNQ_org_Material",
        ),
        migrations.AddIndex(
            model_name="actualcounts",
            index=models.Index(
                fields=["org", "CountDate", "Material"],
                name="WICS_actual_org_id_7d99cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actualcounts",
            index=models.Index(
                fields=["org", "Material"], name="WICS_actual_org_id_b3f861_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actualcounts",
            index=models.Index(
                fields=["org", "BLDG", "LOCATION"], name="WICS_actual_org_id_959f79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sap_sohrecs",
            index=models.Index(
                fields=["uploaded_at", "org", "Material"],
                name="WICS_sap_so_uploade_29626d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="countschedule",
            constraint=models.UniqueConstraint(
                fields=("org", "CountDate", "Material"),
                name="wics_countschedule_realpk",
            ),
        ),
        migrations.AddConstraint(
            model_name="materiallist",
            constraint=models.UniqueConstraint(
                fields=("org", "Material"), name="wics_materiallist_realpk"
            ),
        ),
    ]
