# Generated by Django 4.1.1 on 2023-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WICS", "0022_remove_countschedule_cschdunq_org_cdate_material_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="countschedule",
            name="wics_countschedule_realpk",
        ),
        migrations.RemoveConstraint(
            model_name="materiallist",
            name="wics_materiallist_realpk",
        ),
        migrations.AddConstraint(
            model_name="countschedule",
            constraint=models.UniqueConstraint(
                fields=("org", "CountDate", "Material"),
                name="wics_countschedule_realpk2",
            ),
        ),
        migrations.AddConstraint(
            model_name="materiallist",
            constraint=models.UniqueConstraint(
                fields=("org", "Material"), name="wics_materiallist_realpk2"
            ),
        ),
    ]
