# Generated by Django 4.1.1 on 2023-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WICS", "0024_remove_countschedule_wics_countschedule_realpk2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VIEW_LastSAP",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Material", models.CharField(max_length=100)),
                ("Material_id", models.IntegerField()),
                ("Plant", models.CharField(max_length=20)),
                ("StorageLocation", models.CharField(max_length=20)),
                ("BaseUnitofMeasure", models.CharField(max_length=20)),
                ("Amount", models.FloatField()),
                ("Currency", models.CharField(max_length=20)),
                ("ValueUnrestricted", models.FloatField(blank=True)),
                ("UOM", models.CharField(max_length=50)),
                ("UOMText", models.CharField(max_length=100)),
                ("DimensionText", models.CharField(max_length=100)),
                ("mult", models.FloatField()),
                ("SpecialStock", models.CharField(max_length=20)),
                ("Batch", models.CharField(max_length=20)),
                (
                    "Description",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "SAPMaterialType",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "SAPMaterialGroup",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("Price", models.FloatField(blank=True, null=True)),
                ("PriceUnit", models.PositiveIntegerField(blank=True, null=True)),
                ("TypicalContainerQty", models.IntegerField(blank=True, null=True)),
                ("TypicalPalletQty", models.IntegerField(blank=True, null=True)),
                ("Notes", models.CharField(blank=True, default="", max_length=250)),
                ("PartType_id", models.IntegerField()),
                ("PartType", models.CharField(max_length=50)),
                ("PartTypePriority", models.SmallIntegerField()),
                ("org_id", models.IntegerField()),
                ("OrgName", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "VIEW_LastSAP",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VIEW_MaterialLocationListWithLastSAP",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("org_id", models.IntegerField()),
                ("Material", models.CharField(blank=True, default="", max_length=100)),
                (
                    "Description",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "SAPMaterialType",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "SAPMaterialGroup",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("Price", models.FloatField(blank=True, null=True)),
                ("PriceUnit", models.PositiveIntegerField(blank=True, null=True)),
                ("TypicalContainerQty", models.IntegerField(blank=True, null=True)),
                ("TypicalPalletQty", models.IntegerField(blank=True, null=True)),
                ("Notes", models.CharField(blank=True, default="", max_length=250)),
                ("PartType_id", models.IntegerField()),
                ("PartType", models.CharField(max_length=50)),
                ("PartTypePriority", models.SmallIntegerField()),
                ("OrgName", models.CharField(max_length=250)),
                ("CountDate", models.DateField()),
                ("FoundAt", models.CharField(max_length=1024)),
                ("SAP_id", models.IntegerField()),
                ("SAPDate", models.DateField()),
                ("Plant", models.CharField(max_length=20)),
                ("StorageLocation", models.CharField(max_length=20)),
                ("Amount", models.FloatField()),
                ("BaseUnitofMeasure", models.CharField(max_length=20)),
                ("Currency", models.CharField(max_length=20)),
                ("ValueUnrestricted", models.FloatField(blank=True)),
                ("UOM", models.CharField(max_length=50)),
                ("UOMText", models.CharField(max_length=100)),
                ("DimensionText", models.CharField(max_length=100)),
                ("mult", models.FloatField()),
                ("SpecialStock", models.CharField(max_length=20)),
                ("Batch", models.CharField(max_length=20)),
                ("DoNotShow", models.BooleanField()),
            ],
            options={
                "db_table": "VIEW_MaterialLocationListWithLastSAP",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="VIEW_MaterialLocationListWithSAP",
        ),
    ]
