# Generated by Django 4.1.2 on 2023-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WICS', '0025_view_lastsap_view_materiallocationlistwithlastsap_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countschedule',
            index=models.Index(fields=['org', 'CountDate', 'Material'], name='WICS_counts_org_id_7f3a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='countschedule',
            index=models.Index(fields=['org', 'Material'], name='WICS_counts_org_id_2bbf80_idx'),
        ),
        migrations.AddIndex(
            model_name='countschedule',
            index=models.Index(fields=['org', 'CountDate'], name='WICS_counts_org_id_6edaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallist',
            index=models.Index(fields=['PartType'], name='WICS_materi_PartTyp_2289dc_idx'),
        ),
    ]
