INSERT INTO WICS_UnitsOfMeasure (UOM, UOMText, DimensionText, Multiplier1)
VALUES
('BAG','Bag','(no dimensions)',1),
('BT','Bottle','(no dimensions)',1),
('CAN','Canister','(no dimensions)',1),
('CAR','Carton','(no dimensions)',1),
('CRT','Crate','(no dimensions)',1),
('CV','Case','(no dimensions)',1),
('DR','Drum','(no dimensions)',1),
('DZ','Dozen','(no dimensions)',12),
('EA','each','(no dimensions)',1),
('GAL','US Gallon','Volume',1),
('GRO','Gross','(no dimensions)',144),
('KPC','KPiece','(no dimensions)',1000),
('L','Liter','Volume',1),
('LB','Pound','Mass',1),
('MG','Milligram','Mass',1),
('ML','Milliliter','Volume',1),
('MM','Millimeter','Length',1),
('MM2','Square millimeter','Area',1),
('NAM','Nanometer','Length',1),
('OZ','Ounce','Mass',1),
('PAA','Pair','(no dimensions)',2),
('PAC','Pack','(no dimensions)',1),
('PAL','Pallet','(no dimensions)',1),
('PC','Piece','(no dimensions)',1),
('PT','Pint, US liquid','Volume',1),
('QT','Quart, US liquid','Volume',1),
('ROL','Roll','(no dimensions)',1),
('TO','Ton','Mass',1),
('TON','US Ton','Mass',1),
('TS','Thousands','(no dimensions)',1000),
('VAL','Value-Only Material','(no dimensions)',1),
('YD','Yards','Length',1),
('YD2','Square Yard','Area',1),
('YD3','Cubic yard','Volume',1),
('µL','Microliter','Volume',1),
('µM','Micrometer','Length',1)
