# Generated by Django 4.0.6 on 2022-11-06 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cMenu', '0004_menugroups_alter_menuitems_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WICS', '0003_alter_actualcounts_flag_movementduringcount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WICSuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cMenu.menugroups')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WICS.organizations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
