# Generated by Django 4.0.6 on 2022-10-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menuCommands',
            fields=[
                ('Command', models.IntegerField(primary_key=True, serialize=False)),
                ('CommandText', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['Command'],
            },
        ),
        migrations.CreateModel(
            name='menuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuID', models.SmallIntegerField()),
                ('OptionNumber', models.SmallIntegerField()),
                ('OptionText', models.CharField(max_length=250)),
                ('Argument', models.CharField(max_length=250)),
                ('PWord', models.CharField(max_length=250)),
                ('TopLine', models.BooleanField()),
                ('BottomLine', models.BooleanField()),
                ('Command', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cMenu.menucommands')),
            ],
            options={
                'ordering': ['MenuID', 'OptionNumber'],
            },
        ),
    ]
