# Generated by Django 4.1.1 on 2022-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="menuCommands",
            fields=[
                (
                    "Command",
                    models.IntegerField(
                        db_column="command", primary_key=True, serialize=False
                    ),
                ),
                (
                    "CommandText",
                    models.CharField(db_column="commandtext", max_length=250),
                ),
            ],
            options={
                "db_table": "zzutilmenucommands",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="menuItems",
            fields=[
                (
                    "MenuID",
                    models.SmallIntegerField(
                        db_column="menuid", primary_key=True, serialize=False
                    ),
                ),
                ("OptionNumber", models.SmallIntegerField(db_column="optionnumber")),
                (
                    "OptionText",
                    models.CharField(db_column="optiontext", max_length=250),
                ),
                ("Argument", models.CharField(db_column="argument", max_length=250)),
                ("PWord", models.CharField(db_column="Password", max_length=250)),
                ("TopLine", models.BooleanField(db_column="topline")),
                ("BottomLine", models.BooleanField(db_column="bottomline")),
            ],
            options={
                "db_table": "zapplmenuitems",
                "managed": False,
            },
        ),
    ]
