# Generated by Django 4.0.6 on 2022-10-28 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='Command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cMenu.menucommands'),
        ),
    ]
