# Generated by Django 4.0.6 on 2022-10-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cMenu', '0002_alter_menuitems_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='Argument',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='BottomLine',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='PWord',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='TopLine',
            field=models.BooleanField(null=True),
        ),
    ]
