# Generated by Django 4.1.1 on 2022-12-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cMenu", "0004_menugroups_alter_menuitems_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="cParameters",
            fields=[
                (
                    "ParmName",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ParmValue", models.CharField(blank=True, default="", max_length=512)),
                ("UserModifiable", models.BooleanField(blank=True, default=True)),
                ("Comments", models.CharField(blank=True, default="", max_length=512)),
            ],
            options={
                "ordering": ["ParmName"],
            },
        ),
    ]
