# Generated by Django 4.1.2 on 2023-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cMenu', '0005_cparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='cGreetings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Greeting', models.CharField(max_length=2000)),
            ],
        ),
    ]
