# Generated by Django 4.1.2 on 2023-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cMenu', '0006_cgreetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgreetings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
