# Generated by Django 4.1.1 on 2023-03-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cMenu", "0007_alter_cgreetings_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="menuitems",
            constraint=models.UniqueConstraint(
                models.F("MenuGroup"),
                models.F("MenuID"),
                models.F("OptionNumber"),
                name="mnuItUNQ_mGrp_mID_OptNum",
            ),
        ),
    ]
