"""
Django settings for django_support project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r$kx79q99%#u#r8taa4x5_3uiym24a5b=ri6wn9zq7czt7^kd8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'calvinc460.pythonanywhere.com',
    '127.0.0.1'
    ]

INTERNAL_IPS = [
    '127.0.0.1',
]

DATE_INPUT_FORMATS = [
    '%m/%d/%Y',
    '%Y-%m-%d',
    ]
DATE_FORMAT = 'Y-m-d'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'widget_tweaks',
    'cMenu',
    'mathematical_expressions_parser',
    'WICS',
    'userprofiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'django_support.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # '/home/calvinc460/WICS-Test/templates',
            'templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'string_if_invalid': 'Calvin is confused',
        },
    },
]

WSGI_APPLICATION = 'django_support.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

from sshtunnel import SSHTunnelForwarder

# Connect to a server using the ssh keys. See the sshtunnel documentation for using password authentication
ssh_tunnel = SSHTunnelForwarder(
    'ssh.pythonanywhere.com',
    # ssh_private_key=PATH_TO_SSH_PRIVATE_KEY,
    # ssh_private_key_password=SSH_PRIVATE_KEY_PASSWORD,
    ssh_username='calvinc460',
    ssh_password='5bmQPj-5eLSC-Ks',
    remote_bind_address=('calvinc460.mysql.pythonanywhere-services.com', 3306),
)
ssh_tunnel.start()
DATABASES = {
    # the new test, MySQL on PythonAnywhere
    'prod': {
        'ENGINE': 'django.db.backends.mysql',
    },
    # the development db, MariaDB on Calvin's home machine
    'dev-home': {
        'ENGINE': 'django.db.backends.mysql',
    },
    'sshtunnel_db': {
        'ENGINE': 'django.db.backends.mysql',
    },
}
DATABASES['default']=DATABASES['dev-home']
# DATABASES['default']=DATABASES['sshtunnel_db']

MEDIA_ROOT = 'W:\\WICSdb'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    'W:/WICSdb/MiscFiles'
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 90    # 90 minutes
SESSION_SAVE_EVERY_REQUEST = True

# number fields set high because MaterialForm has many, many, many subrecords (subforms/fields)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 3500
